#!/usr/bin/env bash
# This script loops through1 to 20

i=1
while [ $i -le 20 ]
do
	case $i in
		4)
			echo "$i"
			echo "bad luck from China"
			i=$(( i + 1 ))
			;;
		9)
			echo "$i"
			echo "bad luck from Japan"
			i=$(( i + 1 ))
			;;
		17)
			echo "$i"
			echo "bad luck from Italy"
			i=$(( i + 1 ))
			;;
		*)
			echo "$i"
			i=$(( i + 1 ))
			;;
	esac
done
