#!/usr/bin/env bash
#Bash script that

pid_file="/var/run/myscript.pid"
echo $$ > $pid_file

function func1()
{
	echo "I hate the kill command"
}

trap func3 15

function func2()
{
	echo "Y U no love me?!"
}

trap func2 2

function func3()
{
	rm -rf 
	exit
}

trap func 3 15

while true
do
    echo "To infinty and beyond"
    sleep 2
done
