#!/usr/bin/env bash
#Bash script that

pid_file="/var/run/myscript.pid"
echo $$ > $pid_file

function func1()
{
	echo "I hate the kill command"
}

trap "func3" SIGTERM

function func2()
{
	echo "Y U no love me?!"
}

trap "func2" SIGINT

function func3()
{
	rm "$pid_file"
	exit
}

trap "func" SIGQUIT SIGTERM

while true
do
    echo "To infinty and beyond"
    sleep 2
done
