#!/usr/bin/env bash
#Bash script that

pid_file="/var/run/myscript.pid"
echo $$ > $pid_file

func1 () {
	echo "I hate the kill command"
}

trap 'func1' 15

func2 () {
	echo "Y U no love me?!"
}

trap 'func2' 2

func3 () {
	rm -rf "$pid_file"
	exit
}

trap 'func3' 3 15

while true
do
    echo "To infinty and beyond"
done
