#!/usr/bin/env bash
#Bash script that
 
if test "$1" == "start"
then
	./manage_my_process &
	echo $! >> /var/run/my_process.pid 
	echo "manage_my_process started"

elif test "$1" == "stop"
then
	kill -KILL "$( pgrep -f manage_my_process )"
	rm -rf /var/run/my_process.pid
	echo "manage_my_process stopped"

elif test "$1" == "restart"
then
	kill -KILL "$( pgrep -f manage_my_process )"
       	rm -rf /var/run/my_process.pid
	./manage_my_process &
	echo "manage_my_process restarted"
fi

if test "$1" == ""
then 
	echo "Usage: manage_my_process {start|stop|restart}"
fi
