#!/usr/bin/env bash
#Write a Bash script that displays:To infinity and beyond indefinitely; With a sleep 2 in between each iteration; iI am invincible!!! when receiving a SIGTERM signal

i=1
while [ $i -gt 0 ]
do
	echo "To infinity and beyond"
	sleep 2
	trap "echo 'I am invincible!!!'" SIGTERM
done
